# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eb3cf8270d24a3b90453247383f2b63a293fa9f4f365a95f73f38e3678b495304515d2e469daccd888ea655c1d709f5bac67343e360d6142ed8100466df2a4b

test:
  secret_key_base: 31b3cfdfbfdf1061467892bd3c3aaa54560eae7343a5e4357cffaf6948c28ae71f319376c98271cf16d951ee95e8162a9a738753a88e1f89785879c157986790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
