default: &default
  adapter: postgresql
  encoding: unicode 
  pool: 5
  port: 5432

development:
  <<: *default
  database: taxiproject_development

test:
  <<: *default
  database: taxiproject_test

production:
  <<: *default
  database: taxiproject_production
  username: taxiproject
  password: <%= ENV['TAXIPROJECT_DATABASE_PASSWORD'] %>
