default: &default
  adapter: postgresql
  encoding: unicode
<<<<<<< HEAD
=======
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
>>>>>>> origin/master
  pool: 5
  port: 5432

development:
  <<: *default
  database: taxiproject_development

test:
  <<: *default
  database: taxiproject_test

production:
  <<: *default
  database: taxiproject_production
  username: taxiproject
  password: <%= ENV['TAXIPROJECT_DATABASE_PASSWORD'] %>
